---
- name: Config template
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "/etc/apache2/conf-available/{{ item.name }}.conf"
    mode: 0644
  notify: Reload apache
  loop: "{{ apache_configs }}"
  when:
    - item.template is defined
    - item.enabled is not defined
      or item.enabled
    - item.available is not defined
      or item.available
  become: true
  tags:
    - apache
    - config
    - template

- name: Config absence
  ansible.builtin.file:
    path: "/etc/apache2/conf-available/{{ item.name }}.conf"
    state: absent
  loop: "{{ apache_configs }}"
  when:
    - item.available is defined
    - not item.available
  become: true
  tags:
    - apache
    - config
    - template

- name: Link presence
  ansible.builtin.file:
    src: "../conf-available/{{ item.name }}.conf"
    path: "/etc/apache2/conf-enabled/{{ item.name }}.conf"
    state: link
  notify: Reload apache
  loop: "{{ apache_configs }}"
  when:
    - item.available is not defined
      or item.available
    - item.enabled is not defined
      or item.enabled
  become: true
  tags:
    - apache
    - config
    - link

- name: Link absence
  ansible.builtin.file:
    path:
      "/etc/apache2/conf-enabled/{{ item.name }}.conf"
    state: absent
  notify: Reload apache
  loop: "{{ apache_configs }}"
  when:
    - item.enabled is defined
    - not item.enabled
  become: true
  tags:
    - apache
    - config
    - link
