---
# tasks file for apache
- name: package
  ansible.builtin.package:
    name: apache2
  become: true
  tags:
    - apache
    - package

- name: service_facts
  ansible.builtin.service_facts:
  tags:
    - apache
    - facts
    - vhost

- import_tasks: configs.yml
  when:
    - apache_configs is defined
    - "'apache2.service' in services"

- import_tasks: modules.yml
  when:
    - apache_modules is defined
    - "'apache2.service' in services"

# - name: "openssl_dhparam"
#   openssl_dhparam:
#     path: "{{ apache_dhparam_file | default('/etc/ssl/dhparams.pem') }}"
#     size: "{{ apache_dhparam.bits | default(omit) }}"
#   become: true
#   tags:
#     - apache
#     - ssl
#     - dhparam

- import_tasks: sites.yml
  when:
    - apache_sites is defined
    - apache_sites | length > 0
    - "'apache2.service' in services"
