---
# tasks file for apache
- name: Package
  ansible.builtin.package:
    name:
      "{{ apache_packages }}"
  become: true
  notify: restart apache
  tags:
    - apache
    - package

- name: Service facts
  ansible.builtin.service_facts:
  tags:
    - apache
    - facts
    - vhost

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  when:
    - apache_configs is defined
    - "'apache2.service' in services"

- name: Modules
  ansible.builtin.import_tasks: modules.yml
  when:
    - apache_modules is defined
    - "'apache2.service' in services"

# - name: Openssl dhparam
#   ansible.builtin.openssl_dhparam:
#     path: "{{ apache_dhparam_file | default('/etc/ssl/dhparams.pem') }}"
#     size: "{{ apache_dhparam.bits | default(omit) }}"
#   become: true
#   tags:
#     - apache
#     - ssl
#     - dhparam

- name: Sites
  ansible.builtin.import_tasks: sites.yml
  when:
    - apache_sites is defined
    - apache_sites | length > 0
    - "'apache2.service' in services"
