---
# tasks file for apache
- name: package
  package:
    name: apache2
  become: true
  tags:
    - apache
    - package

- name: service_facts
  ansible.builtin.service_facts:
  tags:
    - apache
    - facts
    - vhost

- import_tasks: modules.yml
  when:
    - apache_modules is defined
    - "'apache2.service' in services"

# - name: "openssl_dhparam"
#   openssl_dhparam:
#     path: "{{ apache_dhparam_file | default('/etc/ssl/dhparams.pem') }}"
#     size: "{{ apache_dhparam.bits | default(omit) }}"
#   become: true
#   tags:
#     - apache
#     - ssl
#     - dhparam

- block:
    - name: documentroot
      file:
        path: "{{ item.documentroot }}"
        state: directory
        mode: 02775
        owner: www-data
        group: www-data
      loop: "{{ apache_sites }}"
      when:
        - item.documentroot is defined
      tags:
        - apache
        - documentroot

    - name: vhost
      template:
        src: "apache-{{ item.template | default('http-site') }}.conf.j2"
        dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
        mode: 0644
      notify: reload apache
      loop: "{{ apache_sites }}"
      when:
        - item.name != '000-default'
        - item.enabled is not defined
          or item.enabled|lower in ['yes', 'true']
        - item.available is not defined
          or item.available|lower in ['yes', 'true']
      tags:
        - apache
        - vhost
        - template

    - name: vhost absence
      file:
        path: "/etc/apache2/sites-available/{{ item.name }}.conf"
        state: absent
      loop: "{{ apache_sites }}"
      when:
        - item.available is defined
        - item.available|lower in ['no', 'false']
      tags:
        - apache
        - vhost
        - template

    - name: link presence
      file:
        src: "../sites-available/{{ item.name }}.conf"
        path:
          "/etc/apache2/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}.conf"
        state: link
      notify: reload apache
      loop: "{{ apache_sites }}"
      when:
        - not ansible_check_mode
        - item.available is not defined
          or item.available|lower in ['yes', 'true']
        - item.enabled is not defined
          or item.enabled
      tags:
        - apache
        - vhost
        - link

    - name: link absence
      file:
        path:
          "/etc/apache2/sites-enabled/{{ item.index |
          default('') }}{{ item.name }}.conf"
        state: absent
      notify: reload apache
      loop: "{{ apache_sites }}"
      when:
        - item.enabled is defined
        - not item.enabled
      tags:
        - apache
        - vhost
        - link

  become: true
  when:
    - apache_sites is defined
    - apache_sites | length > 0
