---
# handlers file for apache
- name: restart apache
  service:
    name: apache2
    state: restarted
  when:
    - "'apache2.service' in services"

- name: reload apache
  service:
    name: apache2
    state: reloaded
  when:
    - "'apache2.service' in services"
